### ISSUE TITLE
Unable to Deploy and Collect raw eBPF data on Civo K3s

### ISSUE THREAD

**Issue by VishwasSomasekhariah** [sysflow-telemetry/sysflow#99]
**Indicate project**
Deployment

**Describe the bug**
I'm trying to deploy sysflow with sf-processor on a Civo K3s cluster to collect raw eBPF data into a file. The deployment by itself does not give any error but I do not see anything being written to the file.

**Expected behavior**
Expected for the deployment to export raw eBPF data to an output file in JSON format.

**Screenshots**
sfcollector logs
<img width="812" alt="sfcollector_logs" src="https://user-images.githubusercontent.com/115732758/213357626-244dc8da-da94-4125-a646-8349a77c92a7.png">

sfprocessor logs
<img width="587" alt="sfprocessor_logs" src="https://user-images.githubusercontent.com/115732758/213357657-36af8263-d844-42c2-bb1f-631e61adc175.png">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - SysFlow version: v0.5.0
 - Container orchestration framework and version (if applicable): Civo K3s v1.22.11+k3s1 
 - Container runtime (if applicable): containerd://1.5.13-k3s1

**Additional context**
The deployment setup to export the raw eBPF data into a jSON file is not really well documented. It would be helpful if that is documented properly for people who are new to Kubernetes environment. I'm trying to export raw eBPF data in JSON format to a file locally. So, I am not enabling the sfexporter in the values.yaml file.

**Comment by araujof** [comment]
@VishwasSomasekhariah, thanks for reporting this! We have never tried SysFlow (or Falco) on a Civo K3s environment, but based on the architecture (it seems like it's x86\_64, please confirm it by running `uname -a` on your environment), it should work. 

Also, the logs from both the collector and processor seem to indicate that the probe was loaded and that the processor is receiving SysFlow records. I believe you have a typo in your issue: did you mean to say you are using SysFlow 0.5.0? (please confirm). 

Can you try to change the deployment to use the eBPF driver instead of the kernel module? Tip: change [this value](https://github.com/sysflow-telemetry/sf-deployments/blob/37d55847b1797af1b267b37704343c8198293dc1/helm/charts/sf-chart/values.yaml#L114) to true in the configuration of the helm chart.

**Comment by terylt** [comment]
@VishwasSomasekhariah  I think before doing the ebpf probe, I would turn on `enableStats`:

 https://github.com/sysflow-telemetry/sf-deployments/blob/37d55847b1797af1b267b37704343c8198293dc1/helm/charts/sf-chart/values.yaml#L124  Change to true and run.   This should spit out stats every 5 mins to show how many records are exported...  If more than 0 records are generated, then it's likely not an issue with the collector.

**Comment by terylt** [comment]
Looks like the main issue here is that k3 uses a containerd.sock that is in a different directory:  

```
/run/k3s/containerd/containerd.sock
```

As a result, to use k3, we need to mount the /run/k3 directory into container using the helm chart, and set the criPath in the values.yaml file, or on the helm command line via:

```
--set sfcollector.criPath="/run/k3s/containerd/containerd.sock"
``` 

We will try to add this in a future release.

**Comment by VishwasSomasekhariah** [comment]
Thank you @terylt for the support in resolving this issue.
